name: "Setup project"
description: "Sets up project and its dependencies"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      name: Setup Bun

    - uses: actions/setup-node@latest
      name: Setup Node.js
      with:
        node-version: 20

    - shell: bash
      name: Install dependencies
      run: |
        bun install --frozen-lockfile
        bun make:data
        