name: "Setup project"
description: "Sets up project and its dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      name: Setup Node.js
      with:
        node-version: 20
        cache: "pnpm"

    - shell: bash
      name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
        pnpm make:data
        