name: Quality Checks

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write # needed for Biome to write diagnostic comments to PRs

concurrency:
  group: checkCodeQuality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkCodeQuality:
    name: "Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup JS dependencies"
        uses: ./.github/actions/setup-project

      - name: "Check code quality"
        uses: ./.github/actions/check-quality
