name: Deploy Desktop Apps
on:
  push:
    tags:
      - 'v[0-9]+.*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-20.04
          - windows-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'  

      - name: "Setup JS dependencies"
        uses: ./.github/actions/setup-project

      - name: "Check code quality"
        uses: ./.github/actions/check-quality

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'SuperEffective v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'Check the release assets to download and install this version.'
          releaseDraft: true
          prerelease: ${{ !startsWith(github.ref_name, 'v') || (endsWith(github.ref_name, '-nightly') || endsWith(github.ref_name, '-alpha') || endsWith(github.ref_name, '-beta') || endsWith(github.ref_name, '-rc')) }}
